-- BeamNG.drive Lua API Stubs
-- Matrix type for transformations
-- Auto-generated by beamng-api-extractor (Go)

---@meta

---@class MatrixF
MatrixF = {}

--- Creates a new transformation matrix
--- @description Creates a new 4x4 transformation matrix
--- @example local mat = MatrixF()
---@return MatrixF -- The new matrix
function MatrixF() end

--- Sets a column of the matrix
--- @description Sets the specified column of the matrix to the given vector
--- @example mat:setColumn(3, pos)
---@param col integer -- Column index (0-3)
---@param vec vec3 -- Vector to set
---@return nil
function MatrixF:setColumn(col, vec) end

--- Gets a column from the matrix
--- @description Returns the specified column of the matrix as a vector
--- @example local col = mat:getColumn(3)
---@param col integer -- Column index (0-3)
---@return vec3 -- Column vector
function MatrixF:getColumn(col) end
