-- BeamNG.drive Lua API Stubs
-- Oriented bounding box
-- Auto-generated by beamng-api-extractor (Go)

---@meta

---@class OrientedBox3F
OrientedBox3F = {}

--- Creates a new oriented bounding box
-- Creates a new OrientedBox3F for oriented bounding box operations
-- example:  local oobb = OrientedBox3F()
---@return OrientedBox3F -- The new oriented box
function OrientedBox3F() end

--- Sets the oriented box from matrix and extents
-- Configures the oriented box using a transformation matrix and extents
-- example:  oobb:set2(matrix, extents)
---@param matrix MatrixF -- Transformation matrix
---@param extents vec3 -- Box extents
---@return nil
function OrientedBox3F:set2(matrix, extents) end

--- Gets an axis of the oriented box
-- Returns one of the three axes of the oriented box
-- example:  local axis = oobb:getAxis(0)
---@param index integer -- Axis index (0, 1, or 2)
---@return vec3 -- The axis vector
function OrientedBox3F:getAxis(index) end

--- Gets the center of the box
-- Returns the center position of the oriented box
-- example:  local center = oobb:getCenter()
---@return vec3 -- Center position
function OrientedBox3F:getCenter() end

--- Gets the half extents of the box
-- Returns the half extents of the oriented box
-- example:  local halfExtents = oobb:getHalfExtents()
---@return vec3 -- Half extents
function OrientedBox3F:getHalfExtents() end
