-- BeamNG.drive Lua API Stubs
-- Quaternion type for rotations
-- Auto-generated by beamng-api-extractor (Go)

---@meta

---@class quat
---@field public x number X component
---@field public y number Y component
---@field public z number Z component
---@field public w number W component
quat = {}

--- Creates a new quaternion for rotation
-- Creates a new quaternion with x, y, z, w components
-- example:  local rot = quat(0, 0, 0, 1)
---@param x number -- X component
---@param y number -- Y component
---@param z number -- Z component
---@param w number -- W component
---@return quat -- The new quaternion
function quat(x, y, z, w) end
