-- BeamNG.drive Lua API Stubs
-- 3D vector type
-- Auto-generated by beamng-api-extractor (Go)

---@meta

---@class vec3
---@field x number X component
---@field y number Y component
---@field z number Z component
vec3 = {}

--- Creates a new 3D vector
-- Creates a new vec3 with the specified x, y, z components
-- example:  local pos = vec3(1, 2, 3)
---@param x number -- X component
---@param y number -- Y component
---@param z number -- Z component
---@return vec3 -- The new vector
function vec3(x, y, z) end
