-- BeamNG.drive Lua API Stubs
-- Module: be
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 56

---@meta

---@class be
be = {}

--- addObject
-- Adds an object to the physics simulation
-- example:  be:addObject(object, true)
--- @occurrences 1
---@param object SceneObject -- Object to add
---@param dynamic boolean -- Whether the object is dynamic
---@return SceneObject|nil -- The added object
function be:addObject(object, dynamic) end

--- castRay
-- Casts a ray from origin to end point and returns hit information
-- example:  local hit = be:castRay(pos, pos-vec3(0,0,13))
--- @occurrences 4
---@param origin vec3 -- Ray origin
---@param endPoint vec3 -- Ray end point
---@return table|nil -- Ray hit information
function be:castRay(origin, endPoint) end

--- enterNextVehicle
-- Enters the next or previous vehicle in the sequence
-- example:  be:enterNextVehicle(0, 1)
--- @occurrences 3
---@param player integer -- Player index (usually 0)
---@param direction integer -- 1 for next, -1 for previous, 0 for any
---@return boolean
function be:enterNextVehicle(player, direction) end

--- enterVehicle
-- Makes a player enter a specific vehicle
-- example:  be:enterVehicle(0, playerVehicle)
--- @occurrences 43
---@param player integer -- Player index (usually 0)
---@param vehicle SceneObject|nil -- Vehicle to enter
---@return boolean
function be:enterVehicle(player, vehicle) end

--- executeJS
-- Executes JavaScript code in the UI
-- example:  be:executeJS("console.log('test')")
--- @occurrences 2
---@param jsCode string -- JavaScript code to execute
---@return nil
function be:executeJS(jsCode) end

--- exitVehicle
-- Makes a player exit their current vehicle
-- example:  be:exitVehicle(0)
--- @occurrences 4
---@param player integer -- Player index (usually 0)
---@return boolean
function be:exitVehicle(player) end

--- getEnabled
-- Returns whether the physics simulation is enabled
-- example:  if be:getEnabled() then
--- @occurrences 13
---@return boolean -- True if physics is enabled
function be:getEnabled() end

--- getEnterableObjectCount
-- Returns the number of enterable objects (vehicles)
-- example:  local count = be:getEnterableObjectCount()
--- @occurrences 2
---@return integer -- Number of enterable objects
function be:getEnterableObjectCount() end

--- getFFBConfig
-- Gets the force feedback configuration for a device
-- example:  local ffbConfig = be:getFFBConfig(deviceName)
--- @occurrences 1
---@param deviceName string -- Device name
---@return table|nil -- Force feedback configuration
function be:getFFBConfig(deviceName) end

--- getFileStream
-- Gets the current file stream object
-- example:  local stream = be:getFileStream()
--- @occurrences 2
---@return table|nil -- File stream object
function be:getFileStream() end

--- getGroundModelByID
-- Gets ground model data by its ID
-- example:  local model = be:getGroundModelByID(modelID)
--- @occurrences 1
---@param modelID integer -- Ground model ID
---@return table|nil -- Ground model data
function be:getGroundModelByID(modelID) end

--- getGroundModelCount
-- Returns the number of ground models
-- example:  local count = be:getGroundModelCount()
--- @occurrences 1
---@return integer -- Number of ground models
function be:getGroundModelCount() end

--- getObject
-- Gets a physics object by its index
-- example:  local veh = be:getObject(i)
--- @occurrences 23
---@param index integer -- Object index
---@return SceneObject|nil -- The object at the index
function be:getObject(index) end

--- getObjectActive
-- Checks if an object is active in the physics simulation
-- example:  if be:getObjectActive(vehId) then
--- @occurrences 10
---@param objectID integer -- Object ID
---@return boolean -- True if object is active
function be:getObjectActive(objectID) end

--- getObjectByID
-- Gets a physics object by its ID
-- example:  local veh = be:getObjectByID(vehId)
--- @occurrences 5
---@param id integer -- Object ID
---@return SceneObject|nil -- The object with the given ID
function be:getObjectByID(id) end

--- getObjectCount
-- Returns the number of physics objects
-- example:  for i = 0, be:getObjectCount() - 1 do
--- @occurrences 30
---@return integer -- Number of physics objects
function be:getObjectCount() end

--- getObjectOOBBCenterXYZ
-- Gets the oriented bounding box center of an object
-- example:  local center = be:getObjectOOBBCenterXYZ(objectID)
--- @occurrences 2
---@param objectID integer -- Object ID
---@return vec3 -- Center position
function be:getObjectOOBBCenterXYZ(objectID) end

--- getObjectOOBBHalfAxisXYZ
-- Gets a half axis of the oriented bounding box
-- example:  local axis = be:getObjectOOBBHalfAxisXYZ(objectID, 0)
--- @occurrences 2
---@param objectID integer -- Object ID
---@param axisIndex integer -- 0, 1, or 2 for X, Y, Z
---@return vec3 -- Half axis vector
function be:getObjectOOBBHalfAxisXYZ(objectID, axisIndex) end

--- getObjectOOBBHalfExtentsXYZ
-- Gets the half extents of the oriented bounding box
-- example:  local halfExtents = be:getObjectOOBBHalfExtentsXYZ(objectID)
--- @occurrences 3
---@param objectID integer -- Object ID
---@return vec3 -- Half extents
function be:getObjectOOBBHalfExtentsXYZ(objectID) end

--- getObjectOOBBIsInitialized
-- Checks if the oriented bounding box is initialized
-- example:  if be:getObjectOOBBIsInitialized(objectID) then
--- @occurrences 1
---@param objectID integer -- Object ID
---@return boolean -- True if OOBB is initialized
function be:getObjectOOBBIsInitialized(objectID) end

--- getObjectPositionXYZ
-- Gets the position of an object
-- example:  local pos = be:getObjectPositionXYZ(objectID)
--- @occurrences 1
---@param objectID integer -- Object ID
---@return vec3 -- Object position
function be:getObjectPositionXYZ(objectID) end

--- getPlayerVehicle
-- Gets the vehicle for a player
-- example:  local veh = be:getPlayerVehicle(0)
--- @occurrences 26
---@param player integer -- Player index (usually 0)
---@return BeamNGVehicle|nil -- Player's vehicle
function be:getPlayerVehicle(player) end

--- getPlayerVehicleID
-- Gets the vehicle ID for a player
-- example:  local vehId = be:getPlayerVehicleID(0)
--- @occurrences 185
---@param player integer -- Player index (usually 0)
---@return integer -- Player's vehicle ID
function be:getPlayerVehicleID(player) end

--- getSurfaceHeightBelow
-- Gets the height of the terrain surface below a point
-- example:  local height = be:getSurfaceHeightBelow(pos.x, pos.y, pos.z)
--- @occurrences 21
---@param x number -- X coordinate
---@param y number -- Y coordinate
---@param z number -- Z coordinate
---@return number -- Surface height
function be:getSurfaceHeightBelow(x, y, z) end

--- getTerrainDrivability
-- Gets the drivability value of terrain at a position
-- example:  local drivability = be:getTerrainDrivability(x, y)
--- @occurrences 3
---@param x number -- X coordinate
---@param y number -- Y coordinate
---@return number -- Drivability value (0-1)
function be:getTerrainDrivability(x, y) end

--- getUpdateUIflag
-- Gets the UI update flag
-- example:  if be:getUpdateUIflag() then
--- @occurrences 1
---@return boolean -- UI update flag value
function be:getUpdateUIflag() end

--- loadTireMarks
-- Loads tire marks from a file
-- example:  be:loadTireMarks(filepath)
--- @occurrences 1
---@param filepath string -- Path to tire marks file
---@return boolean -- True if loaded successfully
function be:loadTireMarks(filepath) end

--- physicsInitWorld
-- Initializes the physics world
-- example:  be:physicsInitWorld()
--- @occurrences 1
---@return nil
function be:physicsInitWorld() end

--- physicsStartSimulation
-- Starts the physics simulation
-- example:  be:physicsStartSimulation()
--- @occurrences 1
---@return nil
function be:physicsStartSimulation() end

--- physicsStep
-- Steps the physics simulation forward
-- example:  be:physicsStep(dt)
--- @occurrences 1
---@param deltaTime number -- Time delta in seconds
---@return nil
function be:physicsStep(deltaTime) end

--- physicsStopSimulation
-- Stops the physics simulation
-- example:  be:physicsStopSimulation()
--- @occurrences 2
---@return nil
function be:physicsStopSimulation() end

--- queueAllObjectLua
-- Queues Lua code to execute on all physics objects
-- example:  be:queueAllObjectLua("electrics.toggle_ignition()")
--- @occurrences 12
---@param luaCode string -- Lua code to execute
---@return nil
function be:queueAllObjectLua(luaCode) end

--- queueHookJS
-- Queues a JavaScript hook to be executed in the UI
-- example:  be:queueHookJS(hookID)
--- @occurrences 1
---@param hookID number -- Hook ID
---@return nil
function be:queueHookJS(hookID) end

--- queueJS
-- Queues JavaScript code to be executed in the UI
-- example:  be:queueJS("console.log('test')")
--- @occurrences 2
---@param jsCode string -- JavaScript code to execute
---@return nil
function be:queueJS(jsCode) end

--- queueLuaCommand
-- Queues a Lua command to be executed
-- example:  be:queueLuaCommand("partmgmt.loadLocal('" .. config .. "')")
--- @occurrences 2
---@param luaCode string -- Lua code to execute
---@return nil
function be:queueLuaCommand(luaCode) end

--- queueObjectFastLua
-- Queues Lua code to execute on a specific object (fast path)
-- example:  be:queueObjectFastLua(objectID, luaCode)
--- @occurrences 2
---@param objectID integer -- Object ID
---@param luaCode string -- Lua code to execute
---@return nil
function be:queueObjectFastLua(objectID, luaCode) end

--- queueObjectLua
-- Queues Lua code to execute on a specific physics object
-- example:  be:queueObjectLua(vehId, "extensions.myMod.callback()")
--- @occurrences 68
---@param objectID integer -- Object ID
---@param luaCode string -- Lua code to execute
---@return nil
function be:queueObjectLua(objectID, luaCode) end

--- queueStreamDataJS
-- Queues stream data to be sent to JavaScript
-- example:  be:queueStreamDataJS(streamID)
--- @occurrences 1
---@param streamID number -- Stream ID
---@return nil
function be:queueStreamDataJS(streamID) end

--- reloadAllVehicles
-- Reloads all vehicles in the simulation
-- example:  be:reloadAllVehicles()
--- @occurrences 1
---@return nil
function be:reloadAllVehicles() end

--- reloadCollision
-- Reloads collision data for the world
-- example:  be:reloadCollision(true, true)
--- @occurrences 45
---@param reloadStatic boolean -- Reload static collision
---@param reloadDynamic boolean -- Reload dynamic collision
---@return nil
function be:reloadCollision(reloadStatic, reloadDynamic) end

--- reloadVehicle
-- Reloads a specific vehicle
-- example:  be:reloadVehicle(vehId)
--- @occurrences 1
---@param vehicleID integer -- Vehicle ID to reload
---@return nil
function be:reloadVehicle(vehicleID) end

--- resetGroundModels
-- Resets all ground models to defaults
-- example:  be:resetGroundModels()
--- @occurrences 1
---@return nil
function be:resetGroundModels() end

--- resetTireMarks
-- Clears all tire marks from the world
-- example:  be:resetTireMarks()
--- @occurrences 3
---@return nil
function be:resetTireMarks() end

--- resetVehicle
-- Resets a vehicle to its initial state
-- example:  be:resetVehicle(vehId)
--- @occurrences 5
---@param vehicleID integer -- Vehicle ID to reset
---@return nil
function be:resetVehicle(vehicleID) end

--- saveTireMarks
-- Saves tire marks to a file
-- example:  be:saveTireMarks(filepath)
--- @occurrences 1
---@param filepath string -- Path to save tire marks
---@return boolean -- True if saved successfully
function be:saveTireMarks(filepath) end

--- sendToMailbox
-- Sends data to a named mailbox for inter-object communication
-- example:  be:sendToMailbox("mapData", lpack.encodeBinWorkBuffer(data))
--- @occurrences 13
---@param mailboxName string -- Mailbox name
---@param data string|table -- Serialized data (typically via lpack.encodeBinWorkBuffer)
---@return nil
function be:sendToMailbox(mailboxName, data) end

--- setDynamicCollisionEnabled
-- Enables or disables dynamic collision
-- example:  be:setDynamicCollisionEnabled(true)
--- @occurrences 5
---@param enabled boolean -- Whether to enable dynamic collision
---@return boolean -- Previous state
function be:setDynamicCollisionEnabled(enabled) end

--- setEnabled
-- Enables or disables the physics simulation
-- example:  be:setEnabled(true)
--- @occurrences 3
---@param enabled boolean -- Whether to enable physics
---@return boolean -- Previous state
function be:setEnabled(enabled) end

--- setGroundModel
-- Sets properties of a ground model
-- example:  be:setGroundModel(modelID, modelData)
--- @occurrences 3
---@param modelID integer -- Ground model ID
---@param modelData table -- Ground model properties
---@return nil
function be:setGroundModel(modelID, modelData) end

--- setPhysicsRunning
-- Pauses or resumes physics simulation
-- example:  be:setPhysicsRunning(true)
--- @occurrences 4
---@param running boolean -- Whether physics should run
---@return nil
function be:setPhysicsRunning(running) end

--- setPhysicsSpeedFactor
-- Sets the physics simulation speed factor (1.0 = real time)
-- example:  be:setPhysicsSpeedFactor(0.5)
--- @occurrences 12
---@param speedFactor number -- Speed multiplier (1.0 = normal)
---@return nil
function be:setPhysicsSpeedFactor(speedFactor) end

--- setSeaLevelTemperatureK
-- Sets the sea level temperature in Kelvin
-- example:  be:setSeaLevelTemperatureK(288.15)
--- @occurrences 1
---@param temperatureK number -- Temperature in Kelvin
---@return nil
function be:setSeaLevelTemperatureK(temperatureK) end

--- setSimulationTimeScale
-- Sets the simulation time scale
-- example:  be:setSimulationTimeScale(1.0)
--- @occurrences 2
---@param timeScale number -- Time scale multiplier
---@return nil
function be:setSimulationTimeScale(timeScale) end

--- sfxGetAvailableDevices
-- Gets a list of available audio devices
-- example:  local devices = be:sfxGetAvailableDevices()
--- @occurrences 1
---@return table -- Array of available sound devices
function be:sfxGetAvailableDevices() end

--- toggleEnabled
-- Toggles the physics simulation on or off
-- example:  local newState = be:toggleEnabled()
--- @occurrences 1
---@return boolean -- New enabled state
function be:toggleEnabled() end

--- triggerRaycastClosest
-- Casts a ray and returns the closest hit
-- example:  local hit = be:triggerRaycastClosest(origin, direction)
--- @occurrences 2
---@param origin vec3 -- Ray origin
---@param direction vec3 -- Ray direction
---@return table|nil -- Ray hit information
function be:triggerRaycastClosest(origin, direction) end
