-- BeamNG.drive Lua API Stubs
-- Module: controller
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 41

---@meta

---@class controller
controller = {}

--- applyDefinition
--- @occurrences 2
---@param definition string
---@return nil
function controller:applyDefinition(definition) end

--- beamBroke
--- @occurrences 1
---@param beamID integer|string
---@param energy number
---@return nil
function controller:beamBroke(beamID, energy) end

--- beamDeformed
--- @occurrences 1
---@param beamID integer|string
---@param deformation number
---@return nil
function controller:beamDeformed(beamID, deformation) end

--- cacheAllControllerFunctions
--- @occurrences 4
---@return nil
function controller:cacheAllControllerFunctions() end

--- debugDraw
--- @occurrences 1
---@param focusPos vec3
---@return nil
function controller:debugDraw(focusPos) end

--- getController
--- @occurrences 49
---@param controllerName string
---@return table|nil
function controller:getController(controllerName) end

--- getControllerSafe
--- @occurrences 20
---@param controllerName string
---@return table|nil
function controller:getControllerSafe(controllerName) end

--- getControllersByType
--- @occurrences 12
---@param controllerType string
---@return table
function controller:getControllersByType(controllerType) end

--- getControllersFromPath
--- @occurrences 4
---@param path string
---@return table
function controller:getControllersFromPath(path) end

--- getSensorData
--- @occurrences 5
---@return table
function controller:getSensorData() end

--- getState
--- @occurrences 1
---@return table
function controller:getState() end

--- getStateData
--- @occurrences 3
---@param key string
---@return table|nil
function controller:getStateData(key) end

--- include
--- @occurrences 1
---@return nil
function controller:include() end

--- incrementTimer
--- @occurrences 5
---@param dtSim number
---@return nil
function controller:incrementTimer(dtSim) end

--- init
--- @occurrences 3
---@param jbeamData table
---@return nil
function controller:init(jbeamData) end

--- initLastStage
--- @occurrences 1
---@return nil
function controller:initLastStage() end

--- initSecondStage
--- @occurrences 1
---@return nil
function controller:initSecondStage() end

--- initSounds
--- @occurrences 1
---@return nil
function controller:initSounds() end

--- loadControllerExternal
--- @occurrences 9
---@param name string
---@param path string
---@param config table
---@return table|nil
function controller:loadControllerExternal(name, path, config) end

--- nodeCollision
--- @occurrences 1
---@param contact table
---@return nil
function controller:nodeCollision(contact) end

--- onCouplerAttached
--- @occurrences 1
---@param nodeId integer
---@param obj2id integer
---@param obj2nodeId integer
---@param attachSpeed number
---@param attachEnergy number
---@return nil
function controller:onCouplerAttached(nodeId, obj2id, obj2nodeId, attachSpeed, attachEnergy) end

--- onCouplerDetached
--- @occurrences 1
---@param nodeId integer
---@param obj2id integer
---@param obj2nodeId integer
---@param breakForce number
---@return nil
function controller:onCouplerDetached(nodeId, obj2id, obj2nodeId, breakForce) end

--- onCouplerFound
--- @occurrences 1
---@param nodeId integer
---@param obj2id integer
---@param obj2nodeId integer
---@param nodeDist number
---@return nil
function controller:onCouplerFound(nodeId, obj2id, obj2nodeId, nodeDist) end

--- onGameplayEvent
--- @occurrences 1
---@param eventName string
---@param ... any
---@return nil
function controller:onGameplayEvent(eventName, ...) end

--- reset
--- @occurrences 6
---@return nil
function controller:reset() end

--- resetLastStage
--- @occurrences 1
---@return nil
function controller:resetLastStage() end

--- resetSecondStage
--- @occurrences 1
---@return nil
function controller:resetSecondStage() end

--- resetSounds
--- @occurrences 1
---@return nil
function controller:resetSounds() end

--- serialize
--- @occurrences 1
---@return table
function controller:serialize() end

--- setFreeze
--- @source lua\vehicle\extensions\scenario\functionFreezer.lua:40
--- @occurrences 2
---@param mode boolean
---@return nil
function controller:setFreeze(mode) end

--- setIsUsingGravity
--- @occurrences 1
---@param usingGravity boolean
---@return nil
function controller:setIsUsingGravity(usingGravity) end

--- setIsVisualised
--- @occurrences 2
---@param visualised boolean
---@return nil
function controller:setIsVisualised(visualised) end

--- setParameters
--- @occurrences 1
---@param params table
---@return nil
function controller:setParameters(params) end

--- setState
--- @occurrences 1
---@param state table
---@return nil
function controller:setState(state) end

--- settingsChanged
--- @occurrences 1
---@return nil
function controller:settingsChanged() end

--- unloadControllerExternal
--- @occurrences 9
---@param name string
---@return nil
function controller:unloadControllerExternal(name) end

--- update
--- @occurrences 1
---@param dt number
---@return nil
function controller:update(dt) end

--- updateGFX
--- @occurrences 1
---@param dt number
---@return nil
function controller:updateGFX(dt) end

--- updateGaugeData
--- @occurrences 1
---@param dt number
---@param gaugeData table|nil
---@return nil
function controller:updateGaugeData(dt, gaugeData) end

--- updateSimpleControlButtons
--- @occurrences 1
---@return nil
function controller:updateSimpleControlButtons() end

--- updateWheelsIntermediate
--- @occurrences 1
---@param dt number
---@return nil
function controller:updateWheelsIntermediate(dt) end
