-- BeamNG.drive Lua API Stubs
-- Module: core (LuaSec SSL library)
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 6

---@meta

---@class core
core = {}

--- compression
--- @description Gets the compression method used by an SSL connection
--- @example local comp, err = core.compression(ssl)
--- @occurrences 1
---@param ssl userdata -- SSL connection object
---@return string|nil -- Compression method or nil on error
---@return string|nil -- Error message if failed
function core:compression(ssl) end

--- copyright
--- @description Returns the LuaSec copyright information
--- @example local info = core.copyright()
--- @occurrences 1
---@return string -- Copyright string
function core:copyright() end

--- create
--- @description Creates a new SSL connection from a context
--- @example local s, msg = core.create(ctx)
--- @occurrences 1
---@param ctx userdata -- SSL context
---@return userdata|nil -- SSL connection or nil on error
---@return string|nil -- Error message if failed
function core:create(ctx) end

--- info
--- @description Gets information about an SSL connection
--- @example local str, bits, algbits, protocol = core.info(ssl)
--- @occurrences 1
---@param ssl userdata -- SSL connection object
---@return string|nil -- Cipher info string
---@return integer|nil -- Key bits
---@return integer|nil -- Algorithm bits
---@return string|nil -- Protocol version
function core:info(ssl) end

--- setfd
--- @description Sets the file descriptor for an SSL connection
--- @example core.setfd(s, sock:getfd())
--- @occurrences 1
---@param ssl userdata -- SSL connection object
---@param fd integer -- File descriptor
---@return nil
function core:setfd(ssl, fd) end

--- setmethod
--- @description Sets the SSL method for a context
--- @example core.setmethod(ctx, 'TLSv1_2')
--- @occurrences 1
---@param ctx userdata -- SSL context
---@param method string -- Method name (e.g. 'TLSv1_2')
---@return nil
function core:setmethod(ctx, method) end

