-- BeamNG.drive Lua API Stubs
-- Module: engine
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 11

---@meta

---@class engine
engine = {}

--- activateStarter
--- @occurrences 1
---@return nil
function engine:activateStarter() end

--- cutIgnition
--- @occurrences 5
---@param duration number
---@return nil
function engine:cutIgnition(duration) end

--- deactivateStarter
--- @occurrences 1
---@return nil
function engine:deactivateStarter() end

--- getSoundConfiguration
--- @occurrences 1
---@return table
function engine:getSoundConfiguration() end

--- getTorqueData
--- @occurrences 4
---@return table
function engine:getTorqueData() end

--- resetTempRevLimiter
--- @occurrences 3
---@return nil
function engine:resetTempRevLimiter() end

--- sendTorqueData
--- @occurrences 7
---@return nil
function engine:sendTorqueData() end

--- setEngineSoundParameterList
--- @occurrences 1
---@param soundId integer
---@param params table
---@param channel string
---@return nil
function engine:setEngineSoundParameterList(soundId, params, channel) end

--- setExhaustGainMufflingOffset
--- @occurrences 1
---@param mufflingOffset number
---@param gainOffset number
---@return nil
function engine:setExhaustGainMufflingOffset(mufflingOffset, gainOffset) end

--- setIgnition
--- @occurrences 1
---@param enabled boolean
---@return nil
function engine:setIgnition(enabled) end

--- setTempRevLimiter
--- @occurrences 2
---@param limiterRPM number
---@return nil
function engine:setTempRevLimiter(limiterRPM) end
