-- BeamNG.drive Lua API Stubs
-- Module: guihooks
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 7

---@meta

---@class guihooks
guihooks = {}

--- graph
--- @occurrences 8
---@param firstValue table|nil -- optional first series entry
---@param ... table -- additional series entries {key, value, scale?, unit?, renderNegatives?, colorRGBA?}
---@return table values -- table of normalized series sent
function guihooks.graph(firstValue, ...) end

--- message
--- @occurrences 89
---@param message string
---@param ttl boolean
---@param category integer
---@param icon boolean
---@return nil
function guihooks.message(message, ttl, category, icon) end
    
--- queueStream
--- @occurrences 22
---@param streamName string
---@param data any
---@return nil
function guihooks.queueStream(streamName, data) end

--- reset
--- @occurrences 1
---@return nil
function guihooks.reset() end

--- sendStreams
--- @occurrences 2
---@return nil
function guihooks.sendStreams() end

--- trigger
--- @occurrences 671
---@param eventName string
---@param data any
---@return nil
function guihooks.trigger(eventName, data) end

--- triggerRawJS
--- @occurrences 2
---@param jsCode string
---@return nil
function guihooks.triggerRawJS(jsCode) end

