-- BeamNG.drive Lua API Stubs
-- Module: input
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 14

---@meta

---@class input
input = {}

--- accept
--- @occurrences 1
---@return nil
function input:accept() end

--- event
--- @description Sends an input event to control vehicle inputs
--- @example input.event("steering", 0.5, FILTER_DIRECT, steeringWheelLock, 1, nil, "ai")
--- @occurrences 69
---@param eventName string -- Event name (e.g., "steering", "throttle", "brake", "parkingbrake")
---@param value number -- Event value (-1 to 1 for steering, 0 to 1 for throttle/brake)
---@param filterType integer|string -- Filter type (1, 2, FILTER_DIRECT, FILTER_AI)
---@param lockValue number|nil -- Optional lock value (e.g., steeringWheelLock)
---@param filterCoef number|nil -- Optional filter coefficient
---@param unused any|nil -- Unused parameter
---@param deviceName string|nil -- Device name identifier (e.g., "ai", "ffbCalibration")
---@return nil
function input:event(eventName, value, filterType, lockValue, filterCoef, unused, deviceName) end

--- getMouseInfo
--- @description Gets current mouse position and button information
--- @example local mouseInfo = input.getMouseInfo()
--- @occurrences 5
---@return table -- Mouse info with x, y coordinates and button states
function input:getMouseInfo() end

--- handleNavGraphEvents
--- @occurrences 1
---@param arg1 any
---@param arg2 any
---@param arg3 any
---@param arg4 any
---@param arg5 any
---@param arg6 boolean
---@return any
function input:handleNavGraphEvents(arg1, arg2, arg3, arg4, arg5, arg6) end

--- handleRibbonEvents
--- @occurrences 1
---@param arg1 any
---@param arg2 any
---@param arg3 boolean
---@param arg4 boolean
---@param arg5 any
---@param arg6 any
---@param arg7 any
---@param arg8 any
---@param arg9 any
---@return any
function input:handleRibbonEvents(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) end

--- init
--- @occurrences 1
---@return nil
function input:init() end

--- initSecondStage
--- @occurrences 1
---@return nil
function input:initSecondStage() end

--- read data function for the input instance
--- @source lua\common\libs\luamqtt\mqtt\protocol.lua:508
--- @occurrences 2
---@param size any
---@return any
function input:read_func(size) end

--- reset
--- @occurrences 1
---@return nil
function input:reset() end

--- setAllowedInputSource
--- @description Sets whether an input source is allowed for a specific action
--- @example input.setAllowedInputSource("mouse", "steering", true)
--- @occurrences 6
---@param source string -- Input source name
---@param action string -- Action name
---@param allowed boolean -- Whether source is allowed
---@return nil
function input:setAllowedInputSource(source, action, allowed) end

--- settingsChanged
--- @occurrences 1
---@return nil
function input:settingsChanged() end

--- toggleEvent
--- @description Toggles an input event on/off
--- @example input.toggleEvent("pause")
--- @occurrences 1
---@param eventName string -- Event name to toggle
---@return nil
function input:toggleEvent(eventName) end

--- updateGFX
--- @occurrences 1
---@param dt number
---@return nil
function input:updateGFX(dt) end

--- updateMouseInfo
--- @occurrences 4
---@return nil
function input:updateMouseInfo() end

