-- BeamNG.drive Lua API Stubs
-- Base class for vehicle objects
-- Auto-generated by beamng-api-extractor (Go)

---@meta

---@class obj
---@field public id integer Vehicle ID
obj = {}

--- C++ binding (found 6 usage(s))
---@param beamId integer
---@param force number
---@param speedLimit number
---@param slipForce number
---@param frictionForce number
---@param slipSpeedLimit number
---@param minExtend number
---@param maxExtend number
---@param virtualMassOut number
---@param virtualMass number
---@return number -- Current beam velocity
function obj:actuateBeam(beamId, force, speedLimit, slipForce, frictionForce, slipSpeedLimit, minExtend, maxExtend, virtualMassOut, virtualMass) end

--- C++ binding (found 1 usage(s))
---@param data table
---@return nil
function obj:add(data) end

--- C++ binding (found 2 usage(s))
---@param left number
---@param top number
---@param right number
---@param bottom number
---@param color Color
---@return nil
function obj:addFrameBlurRect(left, top, right, bottom, color) end

--- C++ binding (found 2 usage(s))
---@param node1 integer
---@param node2 integer
---@param relPos number
---@param particleId integer
---@param velocity number
---@param count integer
---@return nil
function obj:addParticleByNodes(node1, node2, relPos, particleId, velocity, count) end

--- C++ binding (found 53 usage(s))
---@param node1 integer
---@param node2 integer
---@param relPos number
---@param particleId integer
---@param velocity number
---@param count integer
---@return nil
function obj:addParticleByNodesRelative(node1, node2, relPos, particleId, velocity, count) end

--- C++ binding (found 1 usage(s))
---@param nodeId integer
---@param normal vec3
---@param nodeVelocity vec3
---@param velocityMultiplier number
---@param width number
---@param particleType integer
---@param count integer
---@return nil
function obj:addParticleVelWidthTypeCount(nodeId, normal, nodeVelocity, velocityMultiplier, width, particleType, count) end

--- C++ binding (found 1 usage(s))
---@param looped integer -- 1 if looped, 0 otherwise
---@return integer -- Rail id
function obj:addRail(looped) end

--- C++ binding (found 1 usage(s))
---@param railId integer
---@param nodeId integer
---@param capped integer
---@param broken integer
---@return nil
function obj:addRailLink(railId, nodeId, capped, broken) end

--- C++ binding (found 1 usage(s))
---@param nodeId integer
---@param railId integer
---@param attached integer
---@param fixToRail integer
---@param tolerance number
---@param spring number
---@param strength number
---@param capStrength number
---@return integer -- Slidenode id
function obj:addSlidenode(nodeId, railId, attached, fixToRail, tolerance, spring, strength, capStrength) end

--- C++ binding (found 1 usage(s))
---@param wheelId integer
---@param nodeId integer
---@return nil
function obj:addWheelNode(wheelId, nodeId) end

--- C++ binding (found 1 usage(s))
---@param axis vec3
---@param torque number
---@param node1 integer
---@param node2 integer
---@param node3 integer
---@return nil
function obj:apply3nodeTorque(axis, torque, node1, node2, node3) end

--- C++ binding (found 1 usage(s))
---@param nodeId integer
---@param linearAccel vec3
---@param angularAccel vec3
---@return nil
function obj:applyClusterLinearAngularAccel(nodeId, linearAccel, angularAccel) end

--- C++ binding (found 4 usage(s))
---@param node1 integer
---@param node2 integer
---@param forceMagnitude number
---@return nil
function obj:applyForce(node1, node2, forceMagnitude) end

--- C++ binding (found 2 usage(s))
---@param node1 integer
---@param node2 integer
---@param forceMagnitude number
---@param duration number
---@return nil
function obj:applyForceTime(node1, node2, forceMagnitude, duration) end

--- C++ binding (found 3 usage(s))
---@param nodeId integer
---@param force vec3
---@return nil
function obj:applyForceVector(nodeId, force) end

--- C++ binding (found 2 usage(s))
---@param torque number
---@param node1 integer
---@param node2 integer
---@param node3 integer
---@return nil
function obj:applyTorqueAxisCouple(torque, node1, node2, node3) end

--- C++ binding (found 3 usage(s))
---@param index integer
---@return SceneObject|nil
function obj:at(index) end

--- C++ binding (found 2 usage(s))
---@param nodeId integer
---@param tag string
---@param strength number
---@param radius number
---@param lockRadius number
---@param latchSpeed number
---@param targets integer
---@return nil
function obj:attachCoupler(nodeId, tag, strength, radius, lockRadius, latchSpeed, targets) end

--- C++ binding (found 1 usage(s))
---@param nodeId integer
---@param otherObjectId integer
---@param otherNodeId integer
---@param strength number
---@param radius number
---@param lockRadius number
---@param latchSpeed number
---@param flags integer
---@return nil
function obj:attachExternalCoupler(nodeId, otherObjectId, otherNodeId, strength, radius, lockRadius, latchSpeed, flags) end

--- C++ binding (found 5 usage(s))
---@param nodeId integer
---@param otherNodeId integer
---@param strength number
---@param radius number
---@param lockRadius number
---@param latchSpeed number
---@param persistLatch boolean
---@return nil
function obj:attachLocalCoupler(nodeId, otherNodeId, strength, radius, lockRadius, latchSpeed, persistLatch) end

--- C++ binding (found 1 usage(s))
---@param enabled boolean
---@return nil
function obj:autoplace(enabled) end

--- C++ binding (found 7 usage(s))
-- Checks if a beam is broken
-- example:  local beamBroken = obj:beamIsBroken(beam.cid)
---@param beamID integer|string -- Beam ID
---@return boolean -- True if beam is broken
function obj:beamIsBroken(beamID) end

--- C++ binding (found 5 usage(s))
-- Breaks a beam by its ID
-- example:  obj:breakBeam(bcid)
---@param beamID integer|string -- Beam ID to break
---@return nil
function obj:breakBeam(beamID) end

--- C++ binding (found 2 usage(s))
---@param triangleID integer
---@return nil
function obj:breakCollisionTriangle(triangleID) end

--- C++ binding (found 1 usage(s))
---@param beamID integer
---@return nil
function obj:breakMeshes(beamID) end

--- C++ binding (found 1 usage(s))
---@param beamID integer
---@return nil
function obj:breakRails(beamID) end

--- C++ binding (found 6 usage(s))
---@return table -- Beam statistics
function obj:calcBeamStats() end

--- C++ binding (found 6 usage(s))
---@param useCurrentMass boolean
---@return vec3
function obj:calcCenterOfGravity(useCurrentMass) end

--- C++ binding (found 2 usage(s))
---@param useCurrentMass boolean
---@return vec3
function obj:calcCenterOfGravityRel(useCurrentMass) end

--- C++ binding (found 2 usage(s))
---@return vec3
function obj:calcCenterOfPressureRel() end

--- C++ binding (found 1 usage(s))
---@return vec3
function obj:calcTotalAeroForces() end

--- C++ binding (found 1 usage(s))
---@param referencePoint vec3
---@return vec3
function obj:calcTotalAeroTorque(referencePoint) end

--- C++ binding (found 2 usage(s))
---@param origin vec3
---@param direction vec3
---@param maxDistance number
---@param pierceWater boolean|nil
---@return number -- Hit distance (maxDistance if clear)
function obj:castRayStatic(origin, direction, maxDistance, pierceWater) end

--- C++ binding (found 1 usage(s))
---@param pressureGroup integer
---@param drag integer
---@return nil
function obj:changePressureGroupDrag(pressureGroup, drag) end

--- C++ binding (found 1 usage(s))
---@return nil
function obj:commitLoad() end

--- C++ binding (found 23 usage(s))
---@param meshData table
---@return nil
function obj:createMesh(meshData) end

--- C++ binding (found 9 usage(s))
---@param eventName string
---@param description string
---@param profileName string
---@param nodeId integer
---@return integer
function obj:createSFXSource(eventName, description, profileName, nodeId) end

--- C++ binding (found 24 usage(s))
---@param eventName string
---@param description string
---@param profileName string
---@param nodeId integer
---@param is2D boolean|integer
---@return integer
function obj:createSFXSource2(eventName, description, profileName, nodeId, is2D) end

--- C++ binding (found 2 usage(s))
---@param tag string
---@param uri string
---@param width integer
---@param height integer
---@param usageMode integer
---@param fps number
---@return nil
function obj:createWebView(tag, uri, width, height, usageMode, fps) end

--- C++ binding (found 19 usage(s))
---@param sourceId integer
---@return nil
function obj:cutSFX(sourceId) end

--- C++ binding (found 2 usage(s))
---@param pressureGroup integer
---@return nil
function obj:deflatePressureGroup(pressureGroup) end

--- C++ binding (found 79 usage(s))
-- Deletes the object from the scene
-- example:  obj:delete()
---@return nil
function obj:delete() end

--- C++ binding (found 6 usage(s))
---@return nil
function obj:deleteObject() end

--- C++ binding (found 1 usage(s))
---@return nil
function obj:deleteSFXSources() end

--- C++ binding (found 4 usage(s))
---@param couplerId integer
---@param force number
---@return nil
function obj:detachCoupler(couplerId, force) end

--- C++ binding (found 1 usage(s))
---@param beamID integer
---@return number
function obj:detectBeamFrequency(beamID) end

--- C++ binding (found 5 usage(s))
---@return nil
function obj:disable() end

--- C++ binding (found 1 usage(s))
---@return nil
function obj:disableCollision() end

--- C++ binding (found 5 usage(s))
---@return nil
function obj:enable() end

--- C++ binding (found 1 usage(s))
---@return nil
function obj:enableCollision() end

--- C++ binding (found 1 usage(s))
---@return nil
function obj:explode() end

--- C++ binding (found 1 usage(s))
---@return table
function obj:findForestItems() end

--- C++ binding (found 1 usage(s))
---@return nil
function obj:finishLoading() end

--- C++ binding (found 1 usage(s))
-- Returns the value of a named field on the object
-- example:  local dist = obj:get('shadowDistance')
---@param fieldName string
---@return string|number|boolean|table|nil
function obj:get(fieldName) end

--- C++ binding (found 1 usage(s))
---@param axis vec3
---@param node1 integer
---@param node2 integer
---@param node3 integer
---@return number
function obj:get3nodeAngularVelocity(axis, node1, node2, node3) end

--- C++ binding (found 23 usage(s))
-- Returns the absolute world position of a node
-- example:  local pos = obj:getAbsNodePosition(nodeID)
---@param nodeID integer|string -- Node ID
---@return vec3 -- Absolute node position
function obj:getAbsNodePosition(nodeID) end

--- C++ binding (found 3 usage(s))
-- Returns whether the object is active
-- example:  if obj:getActive() then
---@return boolean -- True if object is active
function obj:getActive() end

--- C++ binding (found 1 usage(s))
-- Returns the air density at the object's location
-- example:  local density = obj:getAirDensity()
---@return number -- Air density
function obj:getAirDensity() end

--- C++ binding (found 3 usage(s))
-- Returns the airflow speed at the object
-- example:  local airflow = obj:getAirflowSpeed()
---@return number -- Airflow speed
function obj:getAirflowSpeed() end

--- C++ binding (found 3 usage(s))
-- Returns the altitude of the object
-- example:  local alt = obj:getAltitude()
---@return number -- Altitude
function obj:getAltitude() end

--- C++ binding (found 3 usage(s))
-- Returns the list of anchor names
-- example:  local anchors = obj:getAnchorNames()
---@return table -- Array of anchor names
function obj:getAnchorNames() end

--- C++ binding (found 1 usage(s))
---@return vec3
function obj:getAngularVelocityBrakeCouple() end

--- C++ binding (found 3 usage(s))
-- Returns the total number of beams in the object
-- example:  local beamCount = obj:getBeamCount()
---@return integer -- Number of beams
function obj:getBeamCount() end

--- C++ binding (found 1 usage(s))
---@param beamID integer|string
---@return number
function obj:getBeamCurLengthRefRatio(beamID) end

--- C++ binding (found 2 usage(s))
---@param beamID integer|string
---@return number
function obj:getBeamDebugDeformation(beamID) end

--- C++ binding (found 1 usage(s))
---@param beamID integer|string
---@return number
function obj:getBeamDeformation(beamID) end

--- C++ binding (found 1 usage(s))
---@param beamID string
---@return number
function obj:getBeamForce(beamID) end

--- C++ binding (found 1 usage(s))
---@param beamID integer
---@param frequency number
---@param sampleCount integer
---@return number
function obj:getBeamFrequencyAmplitude(beamID, frequency, sampleCount) end

--- C++ binding (found 19 usage(s))
-- Returns the current length of a beam
-- example:  local length = obj:getBeamLength(beamID)
---@param beamID integer|string -- Beam ID
---@return number -- Current beam length
function obj:getBeamLength(beamID) end

--- C++ binding (found 1 usage(s))
---@param beamID integer|string
---@return number
function obj:getBeamLengthRefRatio(beamID) end

--- C++ binding (found 3 usage(s))
---@param beamID integer|string
---@return number
function obj:getBeamRefLength(beamID) end

--- C++ binding (found 5 usage(s))
---@param beamID integer|string
---@return number
function obj:getBeamRestLength(beamID) end

--- C++ binding (found 12 usage(s))
---@param beamID integer|string
---@return number
function obj:getBeamStress(beamID) end

--- C++ binding (found 3 usage(s))
---@param beamID integer|string
---@return number stress
---@return number damping
function obj:getBeamStressDamp(beamID) end

--- C++ binding (found 10 usage(s))
---@param beamID integer|string
---@param nodeID integer|string
---@return vec3
function obj:getBeamVectorFromNode(beamID, nodeID) end

--- C++ binding (found 3 usage(s))
---@param beamID string
---@return vec3
function obj:getBeamVelocity(beamID) end

--- C++ binding (found 1 usage(s))
---@return vec3
function obj:getCameraPosition() end

--- C++ binding (found 1 usage(s))
---@return vec3
function obj:getCenterPosition() end

--- C++ binding (found 152 usage(s))
-- Returns the class name of the object
-- example:  local className = obj:getClassName()
---@return string -- Class name
function obj:getClassName() end

--- C++ binding (found 2 usage(s))
---@param nodeId integer
---@return vec3
function obj:getClusterVelocityWithoutWheels(nodeId) end

--- C++ binding (found 1 usage(s))
---@return integer
function obj:getCollidableTriangleCount() end

--- C++ binding (found 4 usage(s))
---@return integer
function obj:getCount() end

--- C++ binding (found 3 usage(s))
---@return table
function obj:getData() end

--- C++ binding (found 1 usage(s))
---@return string
function obj:getDeclarationLine() end

--- C++ binding (found 30 usage(s))
-- Returns the forward direction vector of the object
-- example:  local dir = obj:getDirectionVector()
---@return vec3 -- Forward direction vector
function obj:getDirectionVector() end

--- C++ binding (found 4 usage(s))
-- Returns the right direction vector of the object
-- example:  local right = obj:getDirectionVectorRight()
---@return vec3 -- Right direction vector
function obj:getDirectionVectorRight() end

--- C++ binding (found 16 usage(s))
-- Returns the up direction vector of the object
-- example:  local up = obj:getDirectionVectorUp()
---@return vec3 -- Up direction vector
function obj:getDirectionVectorUp() end

--- C++ binding (found 1 usage(s))
---@return vec3
function obj:getDirectionVectorUpXYZ() end

--- C++ binding (found 2 usage(s))
-- Gets a dynamic data field value by name
-- example:  local license = vehicle:getDynDataFieldbyName("licenseText", 0)
---@param fieldName string
---@param arrayIndex integer
---@return string|number|boolean|table|nil
function obj:getDynDataFieldbyName(fieldName, arrayIndex) end

--- C++ binding (found 2 usage(s))
---@return table
function obj:getDynamicFields() end

--- C++ binding (found 4 usage(s))
---@return integer
function obj:getEdgeCount() end

--- C++ binding (found 1 usage(s))
---@return table
function obj:getEdgesTable() end

--- C++ binding (found 5 usage(s))
---@return number
function obj:getEnvPressure() end

--- C++ binding (found 26 usage(s))
---@return number
function obj:getEnvTemperature() end

--- C++ binding (found 49 usage(s))
-- Gets a field value by name and index
-- example:  local name = vehicle:getField('name', 0)
---@param fieldName string
---@param index integer|string
---@return string|number|boolean|table|nil
function obj:getField(fieldName, index) end

--- C++ binding (found 1 usage(s))
---@param fieldName string
---@return integer
function obj:getFieldFlags(fieldName) end

--- C++ binding (found 1 usage(s))
---@return table
function obj:getFieldList() end

--- C++ binding (found 1 usage(s))
---@param fieldName string
---@return string
function obj:getFieldType(fieldName) end

--- C++ binding (found 5 usage(s))
---@return table
function obj:getFields() end

--- C++ binding (found 1 usage(s))
---@return table
function obj:getFieldsForEditor() end

--- C++ binding (found 1 usage(s))
---@return string
function obj:getFileName() end

--- C++ binding (found 3 usage(s))
---@return vec3
function obj:getForwardVector() end

--- C++ binding (found 2 usage(s))
---@return number
function obj:getFrontAirflowSpeed() end

--- C++ binding (found 7 usage(s))
---@return vec3
function obj:getFrontPosition() end

--- C++ binding (found 1 usage(s))
---@param matchInternalName boolean|nil
---@return string
function obj:getGeneratedDisplayName(matchInternalName) end

--- C++ binding (found 8 usage(s))
---@return number
function obj:getGravity() end

--- C++ binding (found 1 usage(s))
---@return vec3
function obj:getGravityVector() end

--- C++ binding (found 10 usage(s))
---@return number
function obj:getGroundSpeed() end

--- C++ binding (found 9 usage(s))
---@return string
function obj:getGroup() end

--- C++ binding (found 13 usage(s))
---@param pressureGroup integer
---@return number
function obj:getGroupPressure(pressureGroup) end

--- C++ binding (found 27 usage(s))
-- Returns the object ID
-- example:  aeroData.vehID = obj:getID()
---@return integer -- Object ID
function obj:getID() end

--- C++ binding (found 51 usage(s))
-- Returns the ID of the object
-- example:  local id = obj:getId()
---@return integer -- Object ID
function obj:getId() end

--- C++ binding (found 1 usage(s))
---@return number impactEnergy
---@return number breakEnergy
---@return integer nodeId
---@return integer material1
---@return integer material2
function obj:getImpactDeformEnergyNode() end

--- C++ binding (found 3 usage(s))
---@return integer
function obj:getInitialHeight() end

--- C++ binding (found 5 usage(s))
---@return number
function obj:getInitialLength() end

--- C++ binding (found 1 usage(s))
---@param nodeID integer
---@return vec3
function obj:getInitialNodePosition(nodeID) end

--- C++ binding (found 4 usage(s))
---@return integer
function obj:getInitialWidth() end

--- C++ binding (found 3 usage(s))
---@return string
function obj:getInternalName() end

--- C++ binding (found 2 usage(s))
---@param mailboxName string
---@return string|nil
function obj:getLastMailbox(mailboxName) end

--- C++ binding (found 10 usage(s))
---@param mailboxName string
---@return integer
function obj:getLastMailboxVersion(mailboxName) end

--- C++ binding (found 1 usage(s))
---@return boolean
function obj:getLightEnabled() end

--- C++ binding (found 2 usage(s))
---@return table
function obj:getMaterialNames() end

--- C++ binding (found 1 usage(s))
---@return string
function obj:getModelFile() end

--- C++ binding (found 26 usage(s))
-- Returns the name of the object
-- example:  local objName = obj:getName()
---@return string -- Object name
function obj:getName() end

--- C++ binding (found 4 usage(s))
---@param nodeID integer|string
---@return integer
function obj:getNodeCluster(nodeID) end

--- C++ binding (found 6 usage(s))
-- Returns the total number of nodes in the object
-- example:  local count = obj:getNodeCount()
---@return integer -- Number of nodes
function obj:getNodeCount() end

--- C++ binding (found 1 usage(s))
---@param node1 integer
---@param node2 integer
---@return number
function obj:getNodeForce(node1, node2) end

--- C++ binding (found 1 usage(s))
---@param node1 integer
---@param node2 integer
---@return number forceZ
---@return number forceXY
function obj:getNodeForceNonInertial(node1, node2) end

--- C++ binding (found 5 usage(s))
---@param nodeID string
---@return vec3
function obj:getNodeForceVector(nodeID) end

--- C++ binding (found 1 usage(s))
---@param nodeID integer|string
---@return vec3
function obj:getNodeForceVectorXYZ(nodeID) end

--- C++ binding (found 16 usage(s))
-- Returns the mass of a node
-- example:  local mass = obj:getNodeMass(nodeID)
---@param nodeID integer|string -- Node ID
---@return number -- Node mass
function obj:getNodeMass(nodeID) end

--- C++ binding (found 42 usage(s))
-- Returns the position of a node relative to the object
-- example:  local pos = obj:getNodePosition(nodeID)
---@param nodeID integer|string -- Node ID
---@return vec3 -- Node position
function obj:getNodePosition(nodeID) end

--- C++ binding (found 19 usage(s))
---@param nodeID integer|string
---@return vec3
function obj:getNodePositionRelative(nodeID) end

--- C++ binding (found 1 usage(s))
---@param nodeID integer|string
---@return vec3
function obj:getNodePositionRelativeXYZ(nodeID) end

--- C++ binding (found 2 usage(s))
---@param nodeID integer|string
---@return table
function obj:getNodeTransform(nodeID) end

--- C++ binding (found 1 usage(s))
---@param nodeID integer|string
---@param relative boolean
---@return vec3
function obj:getNodeVelocity(nodeID, relative) end

--- C++ binding (found 4 usage(s))
---@param nodeID integer|string
---@return vec3
function obj:getNodeVelocityVector(nodeID) end

--- C++ binding (found 3 usage(s))
---@param nodeID integer
---@return integer
function obj:getNodeWidth(nodeID) end

--- C++ binding (found 2 usage(s))
---@param node1 integer
---@param node2 integer
---@return vec3
function obj:getNodesVector(node1, node2) end

--- C++ binding (found 6 usage(s))
---@return table -- Bounding box
function obj:getObjBox() end

--- C++ binding (found 1 usage(s))
---@param objectID integer|string
---@return SceneObject|nil
function obj:getObject(objectID) end

--- C++ binding (found 3 usage(s))
---@return table -- Bounding box
function obj:getObjectBox() end

--- C++ binding (found 3 usage(s))
---@param objectId integer
---@return vec3
function obj:getObjectCenterPosition(objectId) end

--- C++ binding (found 1 usage(s))
---@param outTable table -- filled with ids of colliding objects
---@return nil
function obj:getObjectCollisionIds(outTable) end

--- C++ binding (found 3 usage(s))
---@param objectId integer
---@return vec3
function obj:getObjectDirectionVector(objectId) end

--- C++ binding (found 3 usage(s))
---@param objectId integer
---@return vec3
function obj:getObjectDirectionVectorUp(objectId) end

--- C++ binding (found 7 usage(s))
---@param objectId integer
---@return vec3
function obj:getObjectFrontPosition(objectId) end

--- C++ binding (found 7 usage(s))
---@param objectId integer
---@return number
function obj:getObjectInitialLength(objectId) end

--- C++ binding (found 6 usage(s))
---@param objectId integer
---@return number
function obj:getObjectInitialWidth(objectId) end

--- C++ binding (found 4 usage(s))
---@return SceneObject|nil
function obj:getObjects() end

--- C++ binding (found 6 usage(s))
---@return vec3
function obj:getOriginalFrontPositionRelative() end

--- C++ binding (found 19 usage(s))
---@param nodeID integer|string
---@return vec3
function obj:getOriginalNodePositionRelative(nodeID) end

--- C++ binding (found 1 usage(s))
---@return number
function obj:getPeakPeriod() end

--- C++ binding (found 1 usage(s))
---@return number
function obj:getPhysicsDt() end

--- C++ binding (found 1 usage(s))
---@return vec3
function obj:getPitchAngularVelocity() end

--- C++ binding (found 99 usage(s))
-- Returns the world position of the object
-- example:  local pos = obj:getPosition()
---@return vec3 -- World position
function obj:getPosition() end

--- C++ binding (found 7 usage(s))
-- Returns the world position as separate X, Y, Z values
-- example:  local x, y, z = obj:getPositionXYZ()
---@return number x -- X position
---@return number y -- Y position
---@return number z -- Z position
function obj:getPositionXYZ() end

--- C++ binding (found 3 usage(s))
---@return number
function obj:getRealdt() end

--- C++ binding (found 1 usage(s))
---@return number
function obj:getRelativeAirDensity() end

--- C++ binding (found 1 usage(s))
---@return vec3
function obj:getRollAngularVelocity() end

--- C++ binding (found 11 usage(s))
---@return table -- {roll, pitch, yaw}
function obj:getRollPitchYaw() end

--- C++ binding (found 5 usage(s))
---@return vec3
function obj:getRollPitchYawAngularVelocity() end

--- C++ binding (found 1 usage(s))
---@return number roll
---@return number pitch
function obj:getRollPitchYawRad() end

--- C++ binding (found 15 usage(s))
-- Returns the rotation quaternion of the object
-- example:  local rot = obj:getRotation()
---@return quat -- Rotation quaternion
function obj:getRotation() end

--- C++ binding (found 11 usage(s))
---@return vec3
function obj:getScale() end

--- C++ binding (found 14 usage(s))
---@return number
function obj:getSimTime() end

--- C++ binding (found 2 usage(s))
---@return number
function obj:getSimulationTimeScale() end

--- C++ binding (found 1 usage(s))
---@return number slipVelocity
---@return number sideSlip
---@return number slipEnergy
---@return number downForce
---@return number peakForce
---@return number contactDepth
---@return number contactMaterialID1
---@return number contactMaterialID2
function obj:getSlipVelEnergyDownPeakForceDepthMats() end

--- C++ binding (found 2 usage(s))
---@return vec3
function obj:getSmoothRefVelocityXYZ() end

--- C++ binding (found 2 usage(s))
---@return table -- oriented bounding box data
function obj:getSpawnWorldOOBB() end

--- C++ binding (found 2 usage(s))
---@return number
function obj:getStaticFrictionCoef() end

--- C++ binding (found 8 usage(s))
---@param position vec3
---@return number
function obj:getSurfaceHeightBelow(position) end

--- C++ binding (found 1 usage(s))
---@param torsionbarId integer
---@return number
function obj:getTorsionbarDeformation(torsionbarId) end

--- C++ binding (found 10 usage(s))
-- Returns the transform matrix of the object
-- example:  local transform = obj:getTransform()
---@return table -- Transform matrix
function obj:getTransform() end

--- C++ binding (found 1 usage(s))
---@return integer
function obj:getTriangleCount() end

--- C++ binding (found 1 usage(s))
---@return integer
function obj:getUid() end

--- C++ binding (found 7 usage(s))
---@return boolean
function obj:getUpdateUIflag() end

--- C++ binding (found 36 usage(s))
-- Returns the velocity vector of the object
-- example:  local vel = obj:getVelocity()
---@return vec3 -- Velocity vector
function obj:getVelocity() end

--- C++ binding (found 1 usage(s))
---@return vec3
function obj:getVelocityXYZ() end

--- C++ binding (found 2 usage(s))
---@param wheelId integer
---@return table
function obj:getWheel(wheelId) end

--- C++ binding (found 2 usage(s))
---@param wheelId integer
---@return number
function obj:getWheelAvgTemperature(wheelId) end

--- C++ binding (found 2 usage(s))
---@param wheelId integer
---@return number
function obj:getWheelCoreTemperature(wheelId) end

--- C++ binding (found 1 usage(s))
---@param wheelId integer
---@return {angularVelocity:number, angularVelocityBrakeCouple:number, brakeTorqueApplied:number}
function obj:getWheelFFI(wheelId) end

--- C++ binding (found 12 usage(s))
---@return Box3F
function obj:getWorldBox() end

--- C++ binding (found 1 usage(s))
---@return vec3
function obj:getYawAngularVelocity() end

--- C++ binding (found 1 usage(s))
---@return any
function obj:gui() end

--- C++ binding (found 1 usage(s))
---@return integer
function obj:id() end

--- C++ binding (found 1 usage(s))
---@param node1 integer
---@param node2 integer
---@return boolean
function obj:inSameNodeCluster(node1, node2) end

--- C++ binding (found 9 usage(s))
---@param nodeId integer
---@return boolean
function obj:inWater(nodeId) end

--- C++ binding (found 1 usage(s))
---@return integer
function obj:incRefCount() end

--- C++ binding (found 1 usage(s))
-- Refreshes inspector data; return true to force UI refresh
---@return boolean|nil
function obj:inspectUpdate() end

--- C++ binding (found 1 usage(s))
---@param group any
---@return boolean
function obj:isChildOfGroup(group) end

--- C++ binding (found 1 usage(s))
---@return boolean
function obj:isCollidingWithObject() end

--- C++ binding (found 1 usage(s))
---@return boolean
function obj:isEditorDirty() end

--- C++ binding (found 1 usage(s))
---@return boolean
function obj:isGlobalBounds() end

--- C++ binding (found 12 usage(s))
---@return boolean
function obj:isHidden() end

--- C++ binding (found 4 usage(s))
---@return boolean
function obj:isLocked() end

--- C++ binding (found 1 usage(s))
---@param nodeId integer
---@return boolean
function obj:isNodeColliding(nodeId) end

--- C++ binding (found 4 usage(s))
---@return boolean
function obj:isPlayerControlled() end

--- C++ binding (found 1 usage(s))
---@return boolean
function obj:isRotatingBrakeCouple() end

--- C++ binding (found 11 usage(s))
---@param className string
---@return boolean
function obj:isSubClassOf(className) end

--- C++ binding (found 2 usage(s))
---@param triangleID integer
---@return boolean
function obj:isTriangleBroken(triangleID) end

--- C++ binding (found 7 usage(s))
---@param node1 integer
---@param node2 integer
---@return number
function obj:nodeLength(node1, node2) end

--- C++ binding (found 1 usage(s))
---@param node1 integer
---@param node2 integer
---@return number
function obj:nodeSquaredLength(node1, node2) end

--- C++ binding (found 3 usage(s))
---@param node1 integer
---@param node2 integer
---@param referenceVec vec3
---@return number
function obj:nodeVecCos(node1, node2, referenceVec) end

--- C++ binding (found 8 usage(s))
---@param node1 integer
---@param node2 integer
---@param rightVec vec3
---@param forwardVec vec3
---@return number
function obj:nodeVecPlanarCos(node1, node2, rightVec, forwardVec) end

--- C++ binding (found 7 usage(s))
---@param node1 integer
---@param node2 integer
---@return number
function obj:nodeVecPlanarCosRightForward(node1, node2) end

--- C++ binding (found 1 usage(s))
---@return nil
function obj:onEditorDisable() end

--- C++ binding (found 1 usage(s))
---@return nil
function obj:onEditorEnable() end

--- C++ binding (found 32 usage(s))
---@param soundName string
---@return nil
function obj:playSFX(soundName) end

--- C++ binding (found 4 usage(s))
---@param eventName string
---@param nodeId integer
---@param volume number
---@param is2D integer
---@return integer
function obj:playSFXOnce(eventName, nodeId, volume, is2D) end

--- C++ binding (found 18 usage(s))
---@param eventName string
---@param nodeId integer
---@param volume number
---@param pitch number
---@param color integer
---@param texture integer
---@param loop boolean
---@return integer
function obj:playSFXOnceCT(eventName, nodeId, volume, pitch, color, texture, loop) end

--- C++ binding (found 1 usage(s))
---@param eventName string
---@param nodeId integer
---@param volume number
---@param pitch number
---@param color integer
---@param texture integer
---@return integer
function obj:playSFXOnceStaticCT(eventName, nodeId, volume, pitch, color, texture) end

--- C++ binding (found 6 usage(s))
---@return vec3
function obj:postApply() end

--- C++ binding (found 5 usage(s))
-- Prepares the object for field edits in the editor
---@return nil
function obj:preApply() end

--- C++ binding (found 1 usage(s))
-- Updates a prop's transform and animation value
-- example:  obj:propUpdate(prop.pid, pt.x, pt.y, pt.z, pr.x, pr.y, pr.z, true, val, constrainedVal)
---@param propId integer
---@param posX number
---@param posY number
---@param posZ number
---@param rotX number
---@param rotY number
---@param rotZ number
---@param visible boolean
---@param inputValue number
---@param appliedValue number
---@return nil
function obj:propUpdate(propId, posX, posY, posZ, rotX, rotY, rotZ, visible, inputValue, appliedValue) end

--- C++ binding (found 114 usage(s))
-- Queues Lua code to execute in the game engine's Lua VM
-- example:  obj:queueGameEngineLua("guihooks.trigger('Message', 'Hello')")
---@param luaCode string -- Lua code to execute
---@return nil
function obj:queueGameEngineLua(luaCode) end

--- C++ binding (found 1 usage(s))
---@param hookID number
---@return nil
function obj:queueHookJS(hookID) end

--- C++ binding (found 39 usage(s))
-- Queues Lua code to execute in this object's Lua VM
-- example:  obj:queueLuaCommand("electrics.toggle_ignition()")
---@param luaCode string -- Lua code to execute
---@return nil
function obj:queueLuaCommand(luaCode) end

--- C++ binding (found 5 usage(s))
---@param objectID integer
---@param luaCode string
---@return nil
function obj:queueObjectLuaCommand(objectID, luaCode) end

--- C++ binding (found 1 usage(s))
---@param streamID number
---@return nil
function obj:queueStreamDataJS(streamID) end

--- C++ binding (found 2 usage(s))
---@param webViewId integer
---@param jsCode string
---@return nil
function obj:queueWebViewJS(webViewId, jsCode) end

--- C++ binding (found 1 usage(s))
---@param webViewId integer
---@param streamId integer
---@param jsCode string
---@return nil
function obj:queueWebViewStreamJS(webViewId, streamId, jsCode) end

--- C++ binding (found 1 usage(s))
---@param origin vec3
---@param direction vec3
---@return number -- distance or math.huge if no hit
function obj:rayIntersectsZone(origin, direction) end

--- C++ binding (found 28 usage(s))
---@param name string
---@param persistent boolean|nil
---@return boolean
function obj:registerObject(name, persistent) end

--- C++ binding (found 2 usage(s))
---@return nil
function obj:reloadTextures() end

--- C++ binding (found 3 usage(s))
---@param resetType integer|nil
---@return nil
function obj:requestReset(resetType) end

--- C++ binding (found 1 usage(s))
---@return nil
function obj:resetBrokenFlexMesh() end

--- C++ binding (found 3 usage(s))
---@param materialIndex integer|nil
---@return nil
function obj:resetMaterials(materialIndex) end

--- C++ binding (found 1 usage(s))
-- Actuates a screw-type beam and returns its linear velocity
-- example:  local v = obj:screwBeam(cid, force, speedLimit, math.huge, math.cos(leadAngle), 1, 1, frictionForce, 0, 0, minExtend, maxExtend)
---@param outId integer
---@param torqueForce number
---@param speedLimit number
---@param slipForce number
---@param helixAngleCos number
---@param face1Cos number
---@param face2Cos number
---@param frictionForceStick number
---@param frictionCoef number
---@param slipSpeedLimit number
---@param minExtend number
---@param maxExtend number
---@return number
function obj:screwBeam(outId, torqueForce, speedLimit, slipForce, helixAngleCos, face1Cos, face2Cos, frictionForceStick, frictionCoef, slipSpeedLimit, minExtend, maxExtend) end

--- C++ binding (found 1 usage(s))
-- Sends RPM LED information to a force-feedback device
-- example:  obj:sendRPMLeds(FFBID, currentRPM, rpmFirstLedTurnsOn, rpmRedLine)
---@param deviceId integer
---@param currentRPM number
---@param rpmFirstLedTurnsOn number
---@param rpmRedLine number
---@return nil
function obj:sendRPMLeds(deviceId, currentRPM, rpmFirstLedTurnsOn, rpmRedLine) end

--- C++ binding (found 1 usage(s))
---@param portId integer
---@return nil
function obj:serialPortClose(portId) end

--- C++ binding (found 1 usage(s))
---@param portName string
---@param baudRate integer
---@param mode integer
---@return integer -- port id
function obj:serialPortOpen(portName, baudRate, mode) end

--- C++ binding (found 1 usage(s))
---@param portId integer
---@return string -- data read
function obj:serialPortRead(portId) end

--- C++ binding (found 1 usage(s))
---@param portId integer
---@param data string
---@param length integer
---@return integer -- bytes written
function obj:serialPortWrite(portId, data, length) end

--- C++ binding (found 4 usage(s))
---@param savePhysics boolean
---@param compressionLevel integer
---@return string -- serialized data
function obj:serialize(savePhysics, compressionLevel) end

--- C++ binding (found 1 usage(s))
---@param field string
---@param value any
---@return nil
function obj:set(field, value) end

--- C++ binding (found 4 usage(s))
---@param active boolean
---@return nil
function obj:setActive(active) end

--- C++ binding (found 2 usage(s))
---@param mode integer
---@return nil
function obj:setAerodynamicsMode(mode) end

--- C++ binding (found 1 usage(s))
---@param beamID integer
---@param springExpansion number
---@param dampExpansion number
---@param transitionZone number
---@param longBound number
---@return nil
function obj:setBeamAnisotropic(beamID, springExpansion, dampExpansion, transitionZone, longBound) end

--- C++ binding (found 1 usage(s))
---@param beamId integer
---@param deform number
---@return nil
function obj:setBeamDeform(beamId, deform) end

--- C++ binding (found 1 usage(s))
---@param beamId integer
---@param ratio number
---@return nil
function obj:setBeamDeformationTriggerRatio(beamId, ratio) end

--- C++ binding (found 4 usage(s))
---@param beamID integer
---@param length number
---@return nil
function obj:setBeamLength(beamID, length) end

--- C++ binding (found 1 usage(s))
---@param beamID integer
---@param ratio number
---@return nil
function obj:setBeamLengthRefRatio(beamID, ratio) end

--- C++ binding (found 3 usage(s))
---@param beamID integer
---@param pressure number
---@param maxPressure number
---@param spring number
---@param damp number
---@return nil
function obj:setBeamPressureRel(beamID, pressure, maxPressure, spring, damp) end

--- C++ binding (found 1 usage(s))
---@param beamID integer
---@param pressure number
---@param surface number
---@param volumeCoef number
---@param maxPressure number
---@param pressureLimit number
---@return nil
function obj:setBeamPressured(beamID, pressure, surface, volumeCoef, maxPressure, pressureLimit) end

--- C++ binding (found 11 usage(s))
---@param beamId integer
---@param spring number
---@param damp number
---@param dampFast number|nil
---@param dampVelSplit number|nil
---@return nil
function obj:setBeamSpringDamp(beamId, spring, damp, dampFast, dampVelSplit) end

--- C++ binding (found 1 usage(s))
---@param beamId integer
---@param strength number
---@return nil
function obj:setBeamStrength(beamId, strength) end

--- C++ binding (found 2 usage(s))
---@param beamId integer
---@param damp number
---@param dampFast number
---@param dampVelSplit number
---@param dampBound number
---@param dampReboundFast number
---@param dampReboundVelSplit number
---@return nil
function obj:setBoundedBeamDamp(beamId, damp, dampFast, dampVelSplit, dampBound, dampReboundFast, dampReboundVelSplit) end

--- C++ binding (found 2 usage(s))
---@param beamId integer
---@param longBound number
---@return nil
function obj:setBoundedBeamLongBound(beamId, longBound) end

--- C++ binding (found 1 usage(s))
---@param beamId integer
---@param shortBound number
---@return nil
function obj:setBoundedBeamShortBound(beamId, shortBound) end

--- C++ binding (found 1 usage(s))
---@param beamId integer
---@param spring number
---@param damp number
---@param limit number
---@return nil
function obj:setBoundedBeamSpringDampLimits(beamId, spring, damp, limit) end

--- C++ binding (found 1 usage(s))
---@param canSave boolean
---@return nil
function obj:setCanSave(canSave) end

--- C++ binding (found 5 usage(s))
---@param fieldName string
---@param arrayIndex integer
---@param value any
---@return nil
function obj:setDynDataFieldbyName(fieldName, arrayIndex, value) end

--- C++ binding (found 2 usage(s))
---@param dirty boolean
---@return nil
function obj:setEditorDirty(dirty) end

--- C++ binding (found 1 usage(s))
---@param dataBlock SceneObject|nil
---@return nil
function obj:setEmitterDataBlock(dataBlock) end

--- C++ binding (found 1 usage(s))
---@param node1 integer
---@param node2 integer
---@param node3 integer
---@return nil
function obj:setEngineAxisCoupleNodes(node1, node2, node3) end

--- C++ binding (found 3 usage(s))
-- Updates an engine sound source with current RPM and load data
-- example:  obj:setEngineSound(device.engineSoundID, rpm, scaledLoad, fundamentalFreq, volumeCoef)
---@param soundId integer
---@param rpm number
---@param engineLoad number
---@param fundamentalFreq number
---@param volumeCoef number
---@return nil
function obj:setEngineSound(soundId, rpm, engineLoad, fundamentalFreq, volumeCoef) end

--- C++ binding (found 149 usage(s))
-- Sets a field value on the object
-- example:  obj:setField('shapeName', 0, '/levels/smallgrid/art/shapes/misc/gm_cube_1m.dae')
---@param fieldName string
---@param index integer|string
---@param value string|number
---@return nil
function obj:setField(fieldName, index, value) end

--- C++ binding (found 2 usage(s))
---@param enabled boolean
---@return boolean
function obj:setGhostEnabled(enabled) end

--- C++ binding (found 4 usage(s))
---@param pressureGroup integer
---@param pressure number
---@return nil
function obj:setGroupPressure(pressureGroup, pressure) end

--- C++ binding (found 2 usage(s))
---@param pressureGroup integer
---@param pressure number
---@return nil
function obj:setGroupPressureRel(pressureGroup, pressure) end

--- C++ binding (found 202 usage(s))
---@param hidden boolean
---@return nil
function obj:setHidden(hidden) end

--- C++ binding (found 5 usage(s))
---@param name string
---@return nil
function obj:setInternalName(name) end

--- C++ binding (found 3 usage(s))
---@param materialIndex integer
---@return nil
function obj:setMaterial(materialIndex) end

--- C++ binding (found 1 usage(s))
-- Scales the emissive factor for a material slot
-- example:  obj:setMaterialEmissiveFactor(va.msc, color(255,255,255))
---@param materialSlot integer
---@param emissive Color
---@return nil
function obj:setMaterialEmissiveFactor(materialSlot, emissive) end

--- C++ binding (found 2 usage(s))
---@param alpha number
---@param meshName string
---@return nil
function obj:setMeshAlpha(alpha, meshName) end

--- C++ binding (found 1 usage(s))
---@param paints table -- paint data table
---@return nil
function obj:setMetallicPaintData(paints) end

--- C++ binding (found 8 usage(s))
---@param name string
---@return nil
function obj:setName(name) end

--- C++ binding (found 1 usage(s))
---@param nodeId integer
---@param posX number
---@param posY number
---@param posZ number
---@param weight number
---@param nodeType integer
---@param frictionCoef number
---@param slidingFrictionCoef number
---@param stribeckExponent number
---@param stribeckVelMult number
---@param noLoadCoef number
---@param fullLoadCoef number
---@param loadSensitivitySlope number
---@param softnessCoef number
---@param treadCoef number
---@param tag string
---@param couplerStrength number
---@param firstGroup integer
---@param selfCollision boolean
---@param collision boolean
---@param staticCollision boolean
---@param nodeMaterialTypeID integer
---@return nil
function obj:setNode(nodeId, posX, posY, posZ, weight, nodeType, frictionCoef, slidingFrictionCoef, stribeckExponent, stribeckVelMult, noLoadCoef, fullLoadCoef, loadSensitivitySlope, softnessCoef, treadCoef, tag, couplerStrength, firstGroup, selfCollision, collision, staticCollision, nodeMaterialTypeID) end

--- C++ binding (found 1 usage(s))
---@param nodeId integer
---@param frictionCoef number
---@param slidingFrictionCoef number
---@return nil
function obj:setNodeFrictionSlidingCoefs(nodeId, frictionCoef, slidingFrictionCoef) end

--- C++ binding (found 11 usage(s))
---@param nodeID integer|string
---@param mass number
---@return nil
function obj:setNodeMass(nodeID, mass) end

--- C++ binding (found 1 usage(s))
---@param nodeId integer
---@param pairedNode integer
---@param pairedNode2 integer
---@param wheelId integer
---@return nil
function obj:setNodePair2WheelId(nodeId, pairedNode, pairedNode2, wheelId) end

--- C++ binding (found 1 usage(s))
---@param nodeID integer|string
---@param position vec3
---@return vec3
function obj:setNodePosition(nodeID, position) end

--- C++ binding (found 2 usage(s))
---@param eventId integer
---@param nodeId integer
---@param volume number
---@param pitch number
---@param color number
---@param texture number
---@return nil
function obj:setNodeVolumePitchCT(eventId, nodeId, volume, pitch, color, texture) end

--- C++ binding (found 1 usage(s))
---@param data string -- serialized data
---@return nil
function obj:setPersistentData(data) end

--- C++ binding (found 1 usage(s))
---@param enabled boolean
---@return boolean
function obj:setPhysicsStepEnabled(enabled) end

--- C++ binding (found 7 usage(s))
---@param planets table -- planet data {x, y, z, radius, mass}
---@return nil
function obj:setPlanets(planets) end

--- C++ binding (found 2 usage(s))
---@param x number
---@param y number
---@param z number
---@param rx number
---@param ry number
---@param rz number
---@param rw number
---@return nil
function obj:setPosRot(x, y, z, rx, ry, rz, rw) end

--- C++ binding (found 16 usage(s))
-- Sets the world position of the object
-- example:  obj:setPosition(vec3(-2, 1, 1))
---@param position vec3|number
---@param y number|nil
---@param z number|nil
---@return nil
function obj:setPosition(position, y, z) end

--- C++ binding (found 1 usage(s))
---@param x number
---@param y number
---@param z number
---@param rx number
---@param ry number
---@param rz number
---@param rw number
---@return nil
function obj:setPositionRotation(x, y, z, rx, ry, rz, rw) end

--- Sets the linear velocity of the vehicle
---@param x number Velocity X
---@param y number Velocity Y
---@param z number Velocity Z
---@return nil
function obj:setVelocity(x, y, z) end

--- Sets the angular velocity of the vehicle
---@param x number Angular velocity X
---@param y number Angular velocity Y
---@param z number Angular velocity Z
---@return nil
function obj:setAngularVelocity(x, y, z) end

--- C++ binding (found 1 usage(s))
---@param beamId integer
---@param ratio number
---@return nil
function obj:setPrecompressionRatio(beamId, ratio) end

--- C++ binding (found 1 usage(s))
---@param propId integer
---@param brightness number
---@param flareScale number
---@param color any
---@return nil
function obj:setPropLight(propId, brightness, flareScale, color) end

--- C++ binding (found 1 usage(s))
---@param sourceId integer
---@param keyName string
---@param value number
---@return nil
function obj:setSFXparameter(sourceId, keyName, value) end

--- C++ binding (found 9 usage(s))
-- Sets the uniform scale of the object
-- example:  object:setScale(vec3(2, 2, 2))
---@param scale vec3
---@return nil
function obj:setScale(scale) end

--- C++ binding (found 1 usage(s))
-- Sets per-axis scale components
-- example:  obj:setScaleXYZ(scl.x, scl.y, scl.z)
---@param x number
---@param y number
---@param z number
---@return nil
function obj:setScaleXYZ(x, y, z) end

--- C++ binding (found 3 usage(s))
---@param selected boolean
---@return nil
function obj:setSelected(selected) end

--- C++ binding (found 2 usage(s))
---@param mode integer -- 1=enabled, 2=disabled
---@return nil
function obj:setSelfCollisionMode(mode) end

--- C++ binding (found 1 usage(s))
---@param enabled boolean
---@return boolean
function obj:setSleepingEnabled(enabled) end

--- C++ binding (found 1 usage(s))
---@param threshold integer
---@return nil
function obj:setSlipTireMarkThreshold(threshold) end

--- C++ binding (found 1 usage(s))
---@param path string -- e.g., "/levels/levelname"
---@return nil
function obj:setTerrFileLvlFolder(path) end

--- C++ binding (found 1 usage(s))
---@param torsionbarId integer
---@param angle number
---@param ratio number
---@return nil
function obj:setTorsionbarPrecompressionAngle(torsionbarId, angle, ratio) end

--- C++ binding (found 1 usage(s))
---@param torsionbarId integer
---@param spring number
---@param damp number
---@return nil
function obj:setTorsionbarSpringDamp(torsionbarId, spring, damp) end

--- C++ binding (found 11 usage(s))
-- Sets the transform matrix of the object
-- example:  obj:setTransform(transform)
---@param transform table -- Transform matrix
---@return nil
function obj:setTransform(transform) end

--- C++ binding (found 25 usage(s))
-- Sets the volume of a sound source
-- example:  obj:setVolume(sound, volume)
---@param sourceId integer -- Sound source ID
---@param volume number -- Volume level (0-1)
---@return nil
function obj:setVolume(sourceId, volume) end

--- C++ binding (found 9 usage(s))
---@param sourceId integer
---@param volume number
---@param pitch number
---@param color number|nil
---@param texture number|nil
---@return nil
function obj:setVolumePitch(sourceId, volume, pitch, color, texture) end

--- C++ binding (found 17 usage(s))
---@param sourceId integer
---@param volume number
---@param pitch number
---@param color number
---@param texture number
---@return nil
function obj:setVolumePitchCT(sourceId, volume, pitch, color, texture) end

--- C++ binding (found 1 usage(s))
---@param wheelId integer
---@param torque number
---@param brakeTorque number
---@return nil
function obj:setWheelTorqueAndBrakeTorque(wheelId, torque, brakeTorque) end

--- C++ binding (found 2 usage(s))
---@param x number
---@param y number
---@param z number
---@return nil
function obj:setWind(x, y, z) end

--- C++ binding (found 3 usage(s))
---@return integer
function obj:size() end

--- C++ binding (found 1 usage(s))
---@return nil
function obj:spawnProps() end

--- C++ binding (found 2 usage(s))
---@return nil
function obj:stopLatching() end

--- C++ binding (found 46 usage(s))
---@param soundID number
---@return nil
function obj:stopSFX(soundID) end

--- C++ binding (found 2 usage(s))
---@param meshIndex integer -- material switch combination index
---@param materialName string|nil -- material name or nil to reset
---@return nil
function obj:switchMaterial(meshIndex, materialName) end

--- C++ binding (found 1 usage(s))
---@param torsionbarId integer
---@return boolean
function obj:torsionbarIsBroken(torsionbarId) end

--- C++ binding (found 1 usage(s))
---@return nil
function obj:unload() end

--- C++ binding (found 3 usage(s))
---@param deltaX number
---@param deltaY number
---@return nil
function obj:up(deltaX, deltaY) end

--- C++ binding (found 1 usage(s))
---@return nil
function obj:update() end

--- C++ binding (found 2 usage(s))
---@return nil
function obj:updateInstanceRenderData() end

--- C++ binding (found 3 usage(s))
---@param frontWheelId integer
---@param rearWheelId integer
---@return number
function obj:wheelTurnRadius(frontWheelId, rearWheelId) end
