-- BeamNG.drive Lua API Stubs
-- Module: particles
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 3

---@meta

---@class particles
particles = {}

--- getMaterialIDByName
--- @occurrences 2
---@param materials table
---@param name string
---@return integer
function particles:getMaterialIDByName(materials, name) end

--- getMaterialsParticlesTable
--- @occurrences 7
---@return table materials
---@return table materialsMap
function particles:getMaterialsParticlesTable() end

--- getOrAddMaterialIDByName
--- @occurrences 1
---@param materials table
---@param name string
---@return integer
function particles:getOrAddMaterialIDByName(materials, name) end
