-- BeamNG.drive Lua API Stubs
-- Module: player
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 3

---@meta

---@class player
player = {}

--- getFields
-- Returns a table of field metadata for the player object
--- @occurrences 1
---@return table
function player:getFields() end

--- getPosition
--- @occurrences 2
---@return vec3
function player:getPosition() end

--- getRefNodeMatrix
-- Gets the reference node transform of the player object
--- @occurrences 1
---@return MatrixF
function player:getRefNodeMatrix() end
