-- BeamNG.drive Lua API Stubs
-- Module: profiler
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 3

---@meta

---@class profiler
profiler = {}

--- add
--- @occurrences 17
---@param arg1 string
---@return any
function profiler:add(arg1) end

--- finish
--- @occurrences 7
---@param arg1 boolean
---@return any
function profiler:finish(arg1) end

--- start
--- @occurrences 8
---@return any
function profiler:start() end

