-- BeamNG.drive Lua API Stubs
-- Module: scenetree
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 10

---@meta

---@class scenetree
scenetree = {}

--- used on scenetree object lookups - allows scenetree.objectName syntax
--- @description Metamethod that enables finding objects by name via scenetree.objectName
--- @example local myObject = scenetree.myObjectName
--- @source lua\ge\ge_utils.lua:58
--- @occurrences 1
---@param class_table table -- The scenetree table
---@param memberName string -- Object name to look up
---@return SceneObject|nil -- The found object or nil
function scenetree:__index(class_table, memberName) end

--- the scenetree is read only - prevents assignments
--- @description Metamethod that prevents assignments to scenetree (read-only)
--- @source lua\ge\ge_utils.lua:73
--- @occurrences 1
---@param ... any
---@return nil
function scenetree:__newindex(...) end

--- decalRoadContainsPoint
--- @description Checks if a point is within a decal road object
--- @example if scenetree.decalRoadContainsPoint(roadId, pos) then
--- @source lua\ge\ge_utils.lua:28
--- @occurrences 2
---@param objectId integer -- Decal road object ID
---@param point Point3F -- Point to check
---@return boolean -- True if point is within the road
function scenetree:decalRoadContainsPoint(objectId, point) end

--- allows users to find Objects via classname: scenetree.findClassObjects('BeamNGTrigger')
--- @description Finds all objects of a specific class name
--- @example local triggers = scenetree.findClassObjects('BeamNGTrigger')
--- @source lua\ge\ge_utils.lua:33
--- @occurrences 8
---@param className string -- Class name to search for
---@return table -- Array of matching objects
function scenetree:findClassObjects(className) end

--- allows users to find Objects via name: scenetree.findObject('myname')
--- @description Finds an object by its name
--- @example local obj = scenetree.findObject('myname')
--- @source lua\ge\ge_utils.lua:11
--- @occurrences 27
---@param objectName string -- Object name to search for
---@return SceneObject|nil -- The object or nil if not found
function scenetree:findObject(objectName) end

--- findObjectByIdAsTable
--- @description Finds an object by its ID
--- @example local obj = scenetree.findObjectById(objectId)
--- @source lua\ge\ge_utils.lua:16
--- @occurrences 14
---@param objectId integer -- Object ID to search for
---@return SceneObject|nil -- The object or nil if not found
function scenetree:findObjectById(objectId) end

--- findSubClassObjects
--- @description Finds all objects that are subclasses of a specific class
--- @example local vehicles = scenetree.findSubClassObjects('BeamNGVehicle')
--- @source lua\ge\ge_utils.lua:41
--- @occurrences 1
---@param className string -- Class name to search for subclasses of
---@return table|nil -- Array of matching objects or nil
function scenetree:findSubClassObjects(className) end

--- getAllObjects
--- @description Gets all objects in the scene tree
--- @example local allObjects = scenetree.getAllObjects()
--- @source lua\ge\ge_utils.lua:49
--- @occurrences 2
---@return table|nil -- Array of all scene objects or nil
function scenetree:getAllObjects() end

--- objectExists
--- @description Checks if an object exists by name
--- @example if scenetree.objectExists('myname') then
--- @source lua\ge\ge_utils.lua:20
--- @occurrences 2
---@param objectName string -- Object name to check
---@return boolean -- True if object exists
function scenetree:objectExists(objectName) end

--- objectExistsById
--- @description Checks if an object exists by ID
--- @example if scenetree.objectExistsById(vehId) then
--- @source lua\ge\ge_utils.lua:24
--- @occurrences 2
---@param objectId integer -- Object ID to check
---@return boolean -- True if object exists
function scenetree:objectExistsById(objectId) end
