-- BeamNG.drive Lua API Stubs
-- Module: scenario
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 3

---@meta

---@class scenario
scenario = {}

--- endScreenController
--- @source lua\ge\extensions\campaign\campaigns.lua:391
--- @occurrences 4
---@return any
function scenario:endScreenController() end

--- freeze
--- @occurrences 1
---@param arg1 any
---@return any
function scenario:freeze(arg1) end

--- make
--- @occurrences 1
---@return any
function scenario:make() end

