-- BeamNG.drive Lua API Stubs
-- Module: settings
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 16

---@meta

---@class settings
settings = {}

--- exit
--- @occurrences 1
---@return nil
function settings:exit() end

--- finalizeInit
--- @occurrences 1
---@return nil
function settings:finalizeInit() end

--- getUsedMaterialNames
--- @description Returns a list of material names currently in use
--- @example local materialsUsed = settings.getUsedMaterialNames()
--- @occurrences 2
---@return table -- Array of material name strings
function settings:getUsedMaterialNames() end

--- getValue
--- @description Gets a setting value by key, returning defaultValue if not set
--- @example local target = settings.getValue('uiUnitLength')
--- @occurrences 256
---@param key string -- Setting key name
---@param defaultValue any -- Default value if setting not found
---@return any -- Setting value or default
function settings:getValue(key, defaultValue) end

--- initSettings
--- @occurrences 1
---@param reason any
---@return nil
function settings:initSettings(reason) end

--- load
--- @occurrences 1
---@param ignoreCache boolean
---@return nil
function settings:load(ignoreCache) end

--- notifyUI
--- @occurrences 2
---@return nil
function settings:notifyUI() end

--- onFilesChanged
--- @occurrences 1
---@param files table
---@return nil
function settings:onFilesChanged(files) end

--- refreshTSState
--- @occurrences 3
---@param withValue boolean
---@return nil
function settings:refreshTSState(withValue) end

--- requestSave
--- @occurrences 4
---@return nil
function settings:requestSave() end

--- setState
--- @occurrences 2
---@param newState table
---@param ignoreCache boolean|nil
---@return nil
function settings:setState(newState, ignoreCache) end

--- setValue
--- @occurrences 61
---@param key string
---@param value any
---@param ignoreCache boolean|nil
---@return boolean -- true if state changed
function settings:setValue(key, value, ignoreCache) end

--- settingsChanged
--- @description Invalidates settings cache, called when settings change
--- @example settings.settingsChanged()
--- @occurrences 1
---@return nil
function settings:settingsChanged() end

--- settingsTick
--- @occurrences 1
---@param dtReal number
---@param dtSim number
---@param dtRaw number
---@return nil
function settings:settingsTick(dtReal, dtSim, dtRaw) end

--- updateMaterials
--- @description Updates the materials map for the current vehicle
--- @example settings.updateMaterials()
--- @occurrences 2
---@return nil
function settings:updateMaterials() end

--- write
--- @description Writes settings to persistent storage
--- @occurrences 2
---@return nil
function settings:write() end
