-- BeamNG.drive Lua API Stubs
-- Module: spawn
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 8

---@meta

---@class spawn
spawn = {}

--- calculateRelativeVehiclePlacement
--- @description Builds a transform that aligns two couplers between vehicles
--- @occurrences 1
--- @example local mat = spawn.calculateRelativeVehiclePlacement(transform0, coupler0, coupler1)
---@param transform0 MatrixF
---@param coupler0_offset vec3
---@param coupler1_offset vec3
---@param rotOffset MatrixF|nil
---@return MatrixF
function spawn:calculateRelativeVehiclePlacement(transform0, coupler0_offset, coupler1_offset, rotOffset) end

--- clearCache
--- @description Clears per-frame spawn bounding box cache
--- @occurrences 1
---@return nil
function spawn:clearCache() end

--- pickSpawnPoint
--- @description Returns a valid spawn point for a player/camera
--- @occurrences 1
--- @example local sp = spawn.pickSpawnPoint("player")
---@param spawnName string
---@return SceneObject|nil
function spawn:pickSpawnPoint(spawnName) end

--- placeTrailer
--- @description Positions a trailer relative to a vehicle using coupler offsets
--- @occurrences 3
--- @example spawn.placeTrailer(vehId, vehCouplerOffset, trailerReg[vehId].trailerId, trailerCouplerOffset, vehCouplerTag)
---@param vehId integer
---@param couplerOffsetVeh vec3
---@param trailerId integer
---@param couplerOffsetTrailer vec3
---@param couplerTag string
---@param rotOffset MatrixF|nil
---@return nil
function spawn:placeTrailer(vehId, couplerOffsetVeh, trailerId, couplerOffsetTrailer, couplerTag, rotOffset) end

--- safeTeleport
--- @description Teleports a vehicle safely, avoiding collisions and optionally resetting
--- @occurrences 56
--- @example safeTeleport(veh, pos, rot, nil, nil, nil, true, options.resetVehicle)
---@param veh obj
---@param pos vec3
---@param rot quat|nil
---@param checkOnlyStatics boolean|nil
---@param visibilityPoint vec3|nil
---@param removeTraffic boolean|nil
---@param centeredPosition boolean|nil
---@param resetVehicle boolean|nil
---@return nil
function spawn:safeTeleport(veh, pos, rot, checkOnlyStatics, visibilityPoint, removeTraffic, centeredPosition, resetVehicle) end

--- setVehicleObject
--- @description Applies model, config, paint and options to a vehicle SceneObject
--- @occurrences 2
---@param veh SceneObject
---@param options table
---@return nil
function spawn:setVehicleObject(veh, options) end

--- spawnVehicle
--- @description Creates and registers a vehicle, then sets it up with options
--- @occurrences 12
--- @example local veh = spawn.spawnVehicle(model, partConfig, pos, rot, opt)
---@param model string
---@param partConfig string|table|nil
---@param pos vec3|nil
---@param rot quat|nil
---@param options table|nil
---@return obj|nil
function spawn:spawnVehicle(model, partConfig, pos, rot, options) end

--- teleportToLastRoad
--- @description Teleports a vehicle to its last recovery point on a nearby road
--- @occurrences 4
---@param veh obj|nil
---@param options table|nil
---@return nil
function spawn:teleportToLastRoad(veh, options) end
