-- BeamNG.drive Lua API Stubs
-- Module: TorqueScript
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 2

---@meta

---@class TorqueScript
TorqueScript = {}

--- eval
-- Evaluates TorqueScript code and returns the result
-- example:  TorqueScript.eval('return getSomeValue();')
--- @occurrences 13
---@param code string -- TorqueScript code to evaluate
---@return any -- Result of the evaluation
function TorqueScript:eval(code) end

--- exec
-- Executes a TorqueScript file
-- example:  TorqueScript.exec(filePath)
--- @occurrences 2
---@param filePath string -- Path to the TorqueScript file
---@return any -- Result of execution
function TorqueScript:exec(filePath) end

