-- BeamNG.drive Lua API Stubs
-- Module: UI
-- Auto-generated by beamng-api-extractor (Go)
-- Generated: 2026-01-07 11:33:54
-- Total functions: 12

---@meta

---@class UI
UI = {}

--- buttonImg
-- Creates an image button in the editor UI
-- example:  UI.buttonImg('joints_up', 'link', {30,20}, color)
--- @occurrences 7
---@param id string -- Unique button ID
---@param icon string -- Icon name
---@param size table -- {width, height} size
---@param color integer|table -- Button color
---@param callback any|nil -- Optional callback
---@return boolean -- True if clicked
function UI:buttonImg(id, icon, size, color, callback) end

--- buttonTxt
-- Creates a text button in the editor UI
-- example:  UI.buttonTxt('save', 'Save File', 100, 30)
--- @occurrences 5
---@param id string -- Unique button ID
---@param label string -- Button text
---@param width integer -- Button width
---@param height integer -- Button height
---@return boolean -- True if clicked
function UI:buttonTxt(id, label, width, height) end

--- check
-- Creates a checkbox in the editor UI
-- example:  UI.check('', 'jpart_pick', v.sel)
--- @occurrences 5
---@param label string -- Checkbox label
---@param id string -- Unique checkbox ID
---@param checked boolean -- Current checked state
---@return boolean -- True if state changed
function UI:check(label, id, checked) end

--- columnRight
-- Aligns content to the right side of a column
-- example:  UI.columnRight(100, true)
--- @occurrences 1
---@param width integer -- Column width
---@param separator boolean -- Whether to draw separator
---@return nil
function UI:columnRight(width, separator) end

--- combo
-- Creates a combo dropdown in the editor UI
-- example:  UI.combo('Select', 'combo_id', items, currentIndex)
--- @occurrences 1
---@param label string -- Combo label
---@param id string -- Unique combo ID
---@param items table|any -- Items to display
---@param currentIndex number -- Currently selected index
---@return boolean -- True if selection changed
function UI:combo(label, id, items, currentIndex) end

--- control
-- Creates a generic control element
-- example:  UI.control(type, id, value, config)
--- @occurrences 1
---@param controlType any -- Type of control
---@param id any -- Control ID
---@param value any -- Current value
---@param config any -- Configuration options
---@return any -- Control result
function UI:control(controlType, id, value, config) end

--- hint
-- Displays a hint/tooltip in the UI
-- example:  UI.hint('Click to save')
--- @occurrences 4
---@param text string|any -- Hint text to display
---@return nil
function UI:hint(text) end

--- inject
-- Injects UI elements into a container
-- example:  UI.inject(container, elements)
--- @occurrences 2
---@param container table -- Target container
---@param elements any -- Elements to inject
---@return nil
function UI:inject(container, elements) end

--- slider
-- Creates a slider control in the editor UI
-- example:  UI.slider('Rotate', 'piece_rot', {-180,180})
--- @occurrences 2
---@param label string -- Slider label
---@param id string -- Unique slider ID
---@param range table -- {min, max} value range
---@param flags integer|nil -- Optional flags
---@return boolean -- True if value changed
function UI:slider(label, id, range, flags) end

--- sliderC
-- Creates a centered slider control in the editor UI
-- example:  UI.sliderC('Scale', 'scale_slider', {0,100})
--- @occurrences 2
---@param label string -- Slider label
---@param id string -- Unique slider ID
---@param range table -- {min, max} value range
---@param flags integer|nil -- Optional flags
---@return boolean -- True if value changed
function UI:sliderC(label, id, range, flags) end

--- table
-- Creates a table/grid in the editor UI
-- example:  UI.table('data_table', columns, rows, config)
--- @occurrences 6
---@param id string -- Unique table ID
---@param columns any -- Column definitions
---@param rows any -- Row data
---@param config any -- Table configuration
---@return nil
function UI:table(id, columns, rows, config) end

--- tree2ui
-- Converts a tree structure to UI elements
-- example:  UI.tree2ui(treeData)
--- @occurrences 3
---@param tree any -- Tree structure to convert
---@return nil
function UI:tree2ui(tree) end

